### PR TITLE
Generalize Python Application

### PR DESCRIPTION
**Pull request by maysunfaisal**
Generalizes Python Application:
- Rename python app file from `app.py` to `__main__.py` and update Dockerfile entrypoint command. Renaming to `__main__.py` allows us to execute python without referencing the py file, otherwise we wouldn't know what file to execute in Dockerfile if someone's py executable was named differently.
- Run pip install if `requirements.txt` exist or if one txt file exist

Tested on ODC 4.12 and StoneSoup Staging

### CODE REVIEW

**Review by johnmcollier — COMMENTED** [review]
This should be an improvement compared to before.

But this will only help with portability for python components if `__main__.py` is specified, right? Are there any python projects in https://docs.google.com/spreadsheets/d/1GmEhtReemlVmMgh-nh75AHBCRG2Msc-nEXY4h8owfgY/edit#gid=0 that would be broken with this change (I guess projects that use app.py without a Dockerfile?)?

**Comment by maysunfaisal** [comment]
> This will be an improvement compared to before
> 
> But this will only help with portability for python components if `__main__.py` is specified, right? Are there any python projects in https://docs.google.com/spreadsheets/d/1GmEhtReemlVmMgh-nh75AHBCRG2Msc-nEXY4h8owfgY/edit#gid=0 that would be broken with this change (I guess projects that use app.py without a Dockerfile?)?

yes there is one repo on that list AFAIK that is python and uses app.py.. 

But I guess it is a matter of preference? There is no strong opinion as far as I could tell on the naming convention. The Flask repo here in the example says `app.py` https://github.com/pallets/flask/#a-simple-example but their src code itself has `__main__.py` https://github.com/pallets/flask/tree/main/src/flask

I can undo `__main__.py` but i guess then we will have two point of failure in this sample. Because the Dockerfile command will be `python app.py` 🤔 

@johnmcollier @elsony What do you think? Any strong preference?

**Comment by michael-valdron** [comment]
> I can undo __main__.py but i guess then we will have two point of failure in this sample. Because the Dockerfile command will be python app.py thinking

> @johnmcollier @elsony What do you think? Any strong preference?

Is it best to keep both? Have one refer to the other?

**Review by michael-valdron — COMMENTED** [review]
LGTM other than the current discussion: https://github.com/devfile-samples/devfile-sample-python-basic/pull/26#pullrequestreview-1455732515

**Review by michael-valdron — APPROVED** [review]
/lgtm

**Review by johnmcollier — APPROVED** [review]

**Pull request merged**
